---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: dheeraj7444/countrybank:13
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  labels:
    app: bank
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 31190  # Optional: let Kubernetes assign if not specified
